### ISSUE TITLE
Protocol Level Encryption

### ISSUE THREAD

**Issue by chefsale** [calimero-network/core#178]
Implement encryption based on [Mira’s paper](https://docs.google.com/document/d/1T79zUmrp9Wg5DdJc4Pn_AOfUqybnG0W8PkexUt56u7Q/edit)

**Estimate experimental:** ~2 weeks
**Estimate production:** ~1 month
**Dependencies:** Runtime identity
**Notes:** Look through the libsignal double ratchet algorithm

**Comment by MatejVukosav** [comment]
covered in different task
