### ISSUE TITLE
Informed Garbage Collection 

### ISSUE THREAD

**Issue by chefsale** [calimero-network/core#187]
You can garbage-collect all state transitions up to the last DH reset.
So the oldest state transition you should have cached is the earliest one the oldest active person would need to reconstruct their state.
We can provide a feature on the admin page to show why transactions haven’t been garbage collected, and who they’re being held for.
So you can make informed decisions about whether to remove them from the group, at which point, you can clean up more of those state transitions.
But you can also just delete them at will, and when they come back online, they won’t be fetched from you. But others that (may have them).
Q: what if nobody has the transactions anymore?
Can we just re-add them at a new point, and they discard the old state? We need to really think about this.

**Comment by MatejVukosav** [comment]
We are moving from tx to state diffs. Obsolete
