### ISSUE TITLE
Incorporation of externalities

### ISSUE THREAD

**Issue by chefsale** [calimero-network/core#194]
E.g.  Randomness, on Xchain-data, etc.

[Let’s investigate the determinism](https://github.com/calimero-network/core/issues/271) of third-party sources with regards to Xchain-data. So instead of just injecting a block number, fetch will include a link between the requested object and its response. With the response bound via the [Blob API](https://github.com/calimero-network/core/issues/199).

Question is, if other nodes don’t get to verify the bound response, you can have malicious users who may have tweaked their nodes or used a proxy that gives a false response, everyone will just accept that. Which is questionable, and the alternative of all involved nodes executing live requests is also questionable because the source is non-deterministic.

Here’s our resolve: we’re protecting you from everyone else you don’t deem trustworthy. It’s up to you to act on information received in private groups.

Priority: P3

Dependencies:
 - #186
 
 Sub-issues:
 - [x] #368 
 - [x] #370 
 - [x] #401 
 - [ ] Add more examples for NEAR library

**Comment by MatejVukosav** [comment]
Transferred to https://github.com/calimero-network/core/issues/554
