### ISSUE TITLE
NEAR Integration

### ISSUE THREAD

**Issue by chefsale** [calimero-network/core#206]
This should include the following sub-issues

- [x] #213
- [x] #214

**Comment by chefsale** [comment]
Can we consider this issue closed for now? @miraclx @its-saeed

**Comment by miraclx** [comment]
For clarity, at the moment, we only support reads which is all we're able to impl a safe interface for, we still need investigate how to guard mutability if we want to support writes.

**Comment by MatejVukosav** [comment]
Transferred to integrations
