### ISSUE TITLE
Introducing Application Contexts

### ISSUE THREAD

**Issue by xilosada** [calimero-network/core#228]
Nodes within our network can run multiple contexts simultaneously. This capability facilitates diverse operational environments under a unified framework.
A context in the Calimero Network represents an isolated operational environment where a specific instance of an application runs. Each context functions independently, with its own unique settings and state, allowing for tailored configurations and interactions within the network.
* Every context is separated from others, ensuring that operations within one do not interfere with another. This isolation supports stability and security across multiple application instances.
* When a user creates a context must define the application, the version and the initial setup parameters, creating a customized operational framework for each context.
* Each node generates a unique keypair for each context, used to authenticate and secure transactions specific to that environment. This keypair can be exported from the node allowing users to join the context with other devices.

### Creating a New Context
To initiate a new context:
* Select the desired application and its version (WASM).
* Set up the initial state required for the context.
* Generate a unique context ID
* Persist context configuration

### Joining a Network
A user can be invited to a context, then the user must acknowledge and accept the policies and initial state before proceeding with the network handshake. After a successful handshake users will generate a new keypair for the context and the rest of the network will be aware of they joining the network. After that, the invited user: 
* Dowload the application version if it's not installed in the node
* Initialize the application using the predetermined initial state.
* Subscribe to network events by using the context ID as the topic.
* Reconciliate their context state

### Development contexts
Provide a simple process to run a context in development mode without uploading the application wasm to the registry, For now is can be symlink to the wasm.

**Comment by frdomovic** [comment]
Closing this issue as it is covered in both frontend (admin dashboard) and backend (node + admin api).
The user can on dashboard select application and start multiple separated contexts.
