### ISSUE TITLE
Define the context initialization process at the app level

### ISSUE THREAD

**Issue by miraclx** [calimero-network/core#247]
Right now, `read-only` calls on uninitialized state panics at runtime, while `mutable` calls on "previously"-uninitialized state will delegate to calling `<{AppState} as Default>::default` which makes an assumption on the capacity for the state to be initialized with "default" params. Which may not always be the case.

So.

We need to specify how applications get their initial state.

One option is to use a reserved method called `new` which is idiomatic for Rust, but that would be a weird pattern in other SDKs when we decide to have them

Another approach is to have a custom annotation like `#[app::init]` that informs the codegen logic to treat the return type as the state to be written.

Worth noting that annotated methods *MUST* return `Self`.

And calling them from the node/clients will always return a context ID.

Linked:
- #248

**Comment by MatejVukosav** [comment]
- app init - schema is currently too much work - rather for dev preview call init method with parameters
  - couple context creation with initialization
  - add to docs example of init parameters for our apps  ( op, rps)
  - send params to init function 
  - add init to sdk macro for new init attribute (add init method (mutate method) to initialize contract )

**Comment by miraclx** [comment]
Alright, so I did some thinking.. and being able to manually implement `AppStateInit` without any init method actually being defined is unideal.

This is a non-blocker for this PR, though it's worth thinking through what a better implementation would be.

If we move the initializer method to `AppStateInit`:

```rust
pub trait AppStateInit: Sized {
    type InitParams<'a>: Deserialize<'a>;

    fn init<'a>(params: Self::InitParams<'a>) -> Self;
}
```

and since this returns an explicit `Self`, we can relinquish `Identity` of it's duty _<sub>thanks for your service</sub>_

Now, instead of code-generating an `init` method from the method, we'll move that to `#[app::state]` instead.


```rust
#[cfg(target_arch = "wasm32")]
#[no_mangle]
pub extern "C" fn init() {
    ::calimero_sdk::env::setup_panic_hook();

    ::calimero_sdk::event::register::<#ident>();

    let Some(input) = ::calimero_sdk::env::input() else {
        ::calimero_sdk::env::panic_str("Expected input since method has arguments.")
    };

    let params = match ::calimero_sdk::serde_json::from_slice(&input) {
        Ok(value) => value,
        Err(err) => ::calimero_sdk::env::panic_str(
            &format!("Failed to deserialize input from JSON: {:?}", err)
        ),
    };

    let state = <#ident as ::calimero_sdk::state::AppStateInit>::init(params);

    ::calimero_sdk::env::state_write(&state);
}
```

With that handled, `#[app::init]` becomes the `AppStateInit` definition.

```rust
#[app::logic]
impl Adder {
    #[app::init]
    pub fn init(a: u8, b: u8) -> Adder {
        Adder { a, b }
    }

    pub fn add(&self) -> u8 {
        self.0 + self.1
    }
}
```

expanding to

```rust
impl Adder {
    pub fn init(a: u8, b: u8) -> Adder {
        Adder { a, b }
    }

    pub fn add(&self) -> u8 {
        self.0 + self.1
    }
}

const _: () = {
    struct CalimeroInput {
        a: u8,
        b: u8,
    }

    impl ::calimero_sdk::state::AppStateInit for Adder {
        type InitParams<'a> = CalimeroInput;

        fn init<'a>(
            CalimeroInput {
                a,
                b,
            }: Self::InitParams<'a>,
        ) -> Self {
            Adder::init(a, b)
        }
    }
};

#[cfg(target_arch = "wasm32")]
#[no_mangle]
pub extern "C" fn add() {
    // Snip..
}
```

This forces implementors of `AppStateInit` to also provide the actual initialization logic.

The unfortunate downside of this is, we'll lose the ability to define generics for `#[app::state]`

Although, I suppose there's no good arguments for having them in the first place? Just that we "could".

Even though `#[app::logic]` already forbids the use of generics. So it might make sense to outlaw them for `#[app::state]` to open up this possibility.

_Originally posted by @miraclx in https://github.com/calimero-network/core/issues/532#issuecomment-2251864232_
