### ISSUE TITLE
App installation on client side

### ISSUE THREAD

**Issue by MatejVukosav** [calimero-network/core#477]
Instead of the node making assumptions on the application registry and contract (currently fetching from NEAR testnet on a pre-defined contract `calimero-package-manager.testnet`), the new design of application install from #461 allows the node to consume and store streams of arbitrary data.

The new model for app installation should be:

- From the client side, armed with knowledge of the user's registry source (NEAR mainnet / testnet or wherever else) and the registry contract address, the client retrieves the URL for the application.
- The client makes a request to the node, opening up a stream for a blob upload.
- The client makes a request to the blob URL, piping it's response stream to the node.
- The node responds with a blob ID.
- The client makes a request to the node once more, to create an application record, passing it the `BlobID` and other metadata like a source URL.
- The node responds with an `ApplicationID` == `BlobID`
- The client can now create contexts using the `ApplicationID`

Notable changes in client:
   - frontend : get stream from ipfs and send it to node 

Blocked on #461

**Comment by frdomovic** [comment]
```mermaid
sequenceDiagram
    title App Installation Workflow

    participant Client
    participant Package Manager Contract
    participant Node
    participant IPFS

    Client->>Package Manager Contract: Retrieve IPFS URL for application
    Package Manager Contract->>Client: Application IPFS URL
    Client->>Node: Open stream for blob upload
    Node-->>Client: Blob URL
    Client->>IPFS: Request blob
    IPFS-->>Client: Blob response stream
    Client->>Node: Pipe blob response stream to node
    Node-->>Client: Blob ID
    Client->>Node: Create application record (BlobID & metadata)
    Node-->>Client: ApplicationID == BlobID
    Client->>Node: Create contexts using ApplicationID
```

**Comment by frdomovic** [comment]
cc @miraclx 
```mermaid
sequenceDiagram
    title App Installation Workflow

    participant Client
    participant Package Manager Contract
    participant Node
    participant IPFS

    Client->>Package Manager Contract: Retrieve IPFS URL for application
    Package Manager Contract->>Client: Application IPFS URL
    Client->>Node: Open stream for blob upload
    Node->>Node: Opening stream
    Node-->>Client: Blob URL
    Client->>IPFS: Request blob
    IPFS-->>Client: Blob response stream
    Client->>Node: Pipe blob response stream to node
    Node-->>Client: Blob ID
    Client->>Node: Create application record (BlobID & metadata)
    Node-->>Client: ApplicationID == BlobID
    Client->>Node: Create contexts using ApplicationID
```

**Comment by frdomovic** [comment]
Taking 2 PR's closed into the consideration, is there still something pending from your side or should we close this issue ? @miraclx

**Comment by frdomovic** [comment]
All PR's for this merged. last [pr](https://github.com/calimero-network/core/pull/561)
