### ISSUE TITLE
Option to uninstall application from the node

### ISSUE THREAD

**Issue by frdomovic** [calimero-network/core#524]
## Option to uninstall application from the node

This would also mean all contexts running this application should be removed.
![Screenshot 2024-07-19 at 15 32 46](https://github.com/user-attachments/assets/f7c8343a-adde-44ea-88bd-7da58aabce3c)

**Comment by MatejVukosav** [comment]
I think the direction should be to remove contexts and if there is an application without use, remove the application automatically to free storage.
