### ISSUE TITLE
Node catchup logic and context identity exchange

### ISSUE THREAD

**Issue by fbozic** [calimero-network/core#603]
Tracking issue for node catchup fixes and documentation. Node catchup is not finished feature at the moment.

Documentation:
- Define how the catchup process should look like.
- Define (if needed) how the PublicKey exchange process should look like.

After documentation, fix the current implemenation so it matches.

**Comment by MatejVukosav** [comment]
Deprecating in favour of a new synchronization mechanism using CRDT
