### ISSUE TITLE
expose context ID information to the runtime

### ISSUE THREAD

**Issue by miraclx** [calimero-network/core#790]
Applications should be able to determine under which context ID they are running, this is constant throughout the lifetime of a context, so it poses no risk to determinism.

`calimero_sdk::env` needs to expose a `env::context_id` method, similar to `env::executor_id`:

https://github.com/calimero-network/core/blob/110bafc9245afc7813543f995716fee8c4d0c6ee/crates/sdk/src/env.rs#L121-L125

which should reach for the SDK side of the runtime bridge:

https://github.com/calimero-network/core/blob/110bafc9245afc7813543f995716fee8c4d0c6ee/crates/sdk/src/sys.rs#L15

which would connect to the runtime side:

https://github.com/calimero-network/core/blob/110bafc9245afc7813543f995716fee8c4d0c6ee/crates/runtime/src/logic/imports.rs#L37

and end up in the runtime logic:

https://github.com/calimero-network/core/blob/110bafc9245afc7813543f995716fee8c4d0c6ee/crates/runtime/src/logic.rs#L249-L255

at this point, the `logic.context` needs to be infused with that information

**Comment by chefsale** [comment]
Submitted the PR: https://github.com/calimero-network/core/pull/816.
